package co.panaderia.presentation.admin;

import co.panaderia.presentation.GUILogin;
import static co.panaderia.infra.Messages.successMessage;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Santiago Acuña
 */
public class GUIMenuAdmin extends javax.swing.JFrame {

    /**
     * Variable para controlar los estados de maximizar o minimizar pantalla
     */
    private boolean state = false;
    /**
     * Guarda la coordenada en eje x para poder mover el formulario con el raton
     */
    private int x = 0;
    /**
     * Guarda la coordenada en eje y para poder mover el formulario con el raton
     */
    private int y = 0;
    /**
     * Guarda la instancia del formulario Productos
     */
    private GUIProductos ventaProductos;
    private GUIClientes ventanaClientes;
    private GUIContabilidad ventanaContabilidad;
    private GUIEmpleados ventanaEmpleados;
    private GUIInsumos ventanaInsumos;
    private GUIProveedores ventanaProveedores;

    /**
     * Constructor que inicializa el formulario Menu admin
     *
     * @throws java.beans.PropertyVetoException
     */
    public GUIMenuAdmin() throws PropertyVetoException {
        this.ventaProductos = new GUIProductos();
        this.ventanaClientes = new GUIClientes();
        this.ventanaContabilidad = new GUIContabilidad();
        this.ventanaEmpleados = new GUIEmpleados();
        this.ventanaInsumos = new GUIInsumos();
        this.ventanaProveedores = new GUIProveedores();
        initComponents();
        cargarLista();
        setLocationRelativeTo(null);
        initIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBg = new javax.swing.JPanel();
        jPnlSide = new javax.swing.JPanel();
        BtnHomePage = new javax.swing.JPanel();
        jLbHomePageIcono = new javax.swing.JLabel();
        jLbHomePage = new javax.swing.JLabel();
        BtnProveedores = new javax.swing.JPanel();
        jLbProveedoresIcon = new javax.swing.JLabel();
        jLbProveedores = new javax.swing.JLabel();
        BtnProductos = new javax.swing.JPanel();
        jLbProductosIcon = new javax.swing.JLabel();
        jLbProductos = new javax.swing.JLabel();
        BtnInsumos = new javax.swing.JPanel();
        jLbInsumosIcon = new javax.swing.JLabel();
        jLbInsumos = new javax.swing.JLabel();
        BtnContabilidad = new javax.swing.JPanel();
        jLbContabilidadIcon = new javax.swing.JLabel();
        jLbContabilidad = new javax.swing.JLabel();
        BtnEmpleados = new javax.swing.JPanel();
        jLbEmpleadosIcon = new javax.swing.JLabel();
        jLbEmpleados = new javax.swing.JLabel();
        BtnClientes = new javax.swing.JPanel();
        jLbClientesIcon = new javax.swing.JLabel();
        jLbClientes = new javax.swing.JLabel();
        jLbLogOut = new javax.swing.JLabel();
        jLbUserName = new javax.swing.JLabel();
        jLbUserPhoto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPnlCMH = new javax.swing.JPanel();
        jLbMaxMin = new javax.swing.JLabel();
        jLbHide = new javax.swing.JLabel();
        jLbClose1 = new javax.swing.JLabel();
        dskEscritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPnlBg.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBg.setLayout(new java.awt.BorderLayout());

        jPnlSide.setBackground(new java.awt.Color(54, 33, 88));
        jPnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHomePage.setBackground(new java.awt.Color(85, 65, 118));
        BtnHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnHomePageMousePressed(evt);
            }
        });

        jLbHomePageIcono.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbHomePage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbHomePage.setForeground(new java.awt.Color(204, 204, 204));
        jLbHomePage.setText("Home page");

        javax.swing.GroupLayout BtnHomePageLayout = new javax.swing.GroupLayout(BtnHomePage);
        BtnHomePage.setLayout(BtnHomePageLayout);
        BtnHomePageLayout.setHorizontalGroup(
            BtnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnHomePageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbHomePageIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnHomePageLayout.setVerticalGroup(
            BtnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BtnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbHomePage)
                    .addComponent(jLbHomePageIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 40));

        BtnProveedores.setBackground(new java.awt.Color(64, 43, 100));
        BtnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnProveedoresMousePressed(evt);
            }
        });

        jLbProveedoresIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbProveedores.setForeground(new java.awt.Color(204, 204, 204));
        jLbProveedores.setText("Proveedores");

        javax.swing.GroupLayout BtnProveedoresLayout = new javax.swing.GroupLayout(BtnProveedores);
        BtnProveedores.setLayout(BtnProveedoresLayout);
        BtnProveedoresLayout.setHorizontalGroup(
            BtnProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnProveedoresLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbProveedoresIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnProveedoresLayout.setVerticalGroup(
            BtnProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnProveedoresLayout.createSequentialGroup()
                .addGroup(BtnProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbProveedoresIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnProveedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbProveedores)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 40));

        BtnProductos.setBackground(new java.awt.Color(64, 43, 100));
        BtnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnProductosMousePressed(evt);
            }
        });

        jLbProductosIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbProductos.setForeground(new java.awt.Color(204, 204, 204));
        jLbProductos.setText("Productos");

        javax.swing.GroupLayout BtnProductosLayout = new javax.swing.GroupLayout(BtnProductos);
        BtnProductos.setLayout(BtnProductosLayout);
        BtnProductosLayout.setHorizontalGroup(
            BtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnProductosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbProductosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnProductosLayout.setVerticalGroup(
            BtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnProductosLayout.createSequentialGroup()
                .addGroup(BtnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbProductosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbProductos)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        BtnInsumos.setBackground(new java.awt.Color(64, 43, 100));
        BtnInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnInsumosMousePressed(evt);
            }
        });

        jLbInsumosIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbInsumos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbInsumos.setForeground(new java.awt.Color(204, 204, 204));
        jLbInsumos.setText("Insumos");

        javax.swing.GroupLayout BtnInsumosLayout = new javax.swing.GroupLayout(BtnInsumos);
        BtnInsumos.setLayout(BtnInsumosLayout);
        BtnInsumosLayout.setHorizontalGroup(
            BtnInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnInsumosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbInsumosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnInsumosLayout.setVerticalGroup(
            BtnInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnInsumosLayout.createSequentialGroup()
                .addGroup(BtnInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbInsumosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnInsumosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbInsumos)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 40));

        BtnContabilidad.setBackground(new java.awt.Color(64, 43, 100));
        BtnContabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnContabilidadMousePressed(evt);
            }
        });

        jLbContabilidadIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbContabilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbContabilidad.setForeground(new java.awt.Color(204, 204, 204));
        jLbContabilidad.setText("Contabilidad");

        javax.swing.GroupLayout BtnContabilidadLayout = new javax.swing.GroupLayout(BtnContabilidad);
        BtnContabilidad.setLayout(BtnContabilidadLayout);
        BtnContabilidadLayout.setHorizontalGroup(
            BtnContabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnContabilidadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbContabilidadIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnContabilidadLayout.setVerticalGroup(
            BtnContabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnContabilidadLayout.createSequentialGroup()
                .addGroup(BtnContabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbContabilidadIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnContabilidadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbContabilidad)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnContabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, 40));

        BtnEmpleados.setBackground(new java.awt.Color(64, 43, 100));
        BtnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnEmpleadosMousePressed(evt);
            }
        });

        jLbEmpleadosIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbEmpleados.setForeground(new java.awt.Color(204, 204, 204));
        jLbEmpleados.setText("Empleados");

        javax.swing.GroupLayout BtnEmpleadosLayout = new javax.swing.GroupLayout(BtnEmpleados);
        BtnEmpleados.setLayout(BtnEmpleadosLayout);
        BtnEmpleadosLayout.setHorizontalGroup(
            BtnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnEmpleadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbEmpleadosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnEmpleadosLayout.setVerticalGroup(
            BtnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnEmpleadosLayout.createSequentialGroup()
                .addGroup(BtnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbEmpleadosIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbEmpleados)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, 40));

        BtnClientes.setBackground(new java.awt.Color(64, 43, 100));
        BtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnClientesMousePressed(evt);
            }
        });

        jLbClientesIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbClientes.setForeground(new java.awt.Color(204, 204, 204));
        jLbClientes.setText("Clientes");

        javax.swing.GroupLayout BtnClientesLayout = new javax.swing.GroupLayout(BtnClientes);
        BtnClientes.setLayout(BtnClientesLayout);
        BtnClientesLayout.setHorizontalGroup(
            BtnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnClientesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbClientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BtnClientesLayout.setVerticalGroup(
            BtnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnClientesLayout.createSequentialGroup()
                .addGroup(BtnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbClientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BtnClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbClientes)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(BtnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 40));

        jLbLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLbLogOut.setForeground(new java.awt.Color(204, 204, 204));
        jLbLogOut.setText("Log out");
        jLbLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbLogOutMousePressed(evt);
            }
        });
        jPnlSide.add(jLbLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 50, -1));

        jLbUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLbUserName.setForeground(new java.awt.Color(204, 204, 204));
        jLbUserName.setText("User");
        jLbUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbUserNameMousePressed(evt);
            }
        });
        jPnlSide.add(jLbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));
        jPnlSide.add(jLbUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 100));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPnlSide.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 10));

        jPnlBg.add(jPnlSide, java.awt.BorderLayout.LINE_START);

        jPnlCMH.setBackground(new java.awt.Color(122, 72, 221));
        jPnlCMH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPnlCMHMouseDragged(evt);
            }
        });
        jPnlCMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCMHMousePressed(evt);
            }
        });

        jLbMaxMin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbMaxMin.setForeground(new java.awt.Color(255, 255, 255));
        jLbMaxMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbMaxMin.setText("[]");
        jLbMaxMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbMaxMinMouseClicked(evt);
            }
        });

        jLbHide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbHide.setForeground(new java.awt.Color(255, 255, 255));
        jLbHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbHide.setText("-");
        jLbHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbHideMouseClicked(evt);
            }
        });

        jLbClose1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbClose1.setForeground(new java.awt.Color(255, 255, 255));
        jLbClose1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbClose1.setText("X");
        jLbClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbClose1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlCMHLayout = new javax.swing.GroupLayout(jPnlCMH);
        jPnlCMH.setLayout(jPnlCMHLayout);
        jPnlCMHLayout.setHorizontalGroup(
            jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCMHLayout.createSequentialGroup()
                .addContainerGap(1014, Short.MAX_VALUE)
                .addComponent(jLbHide, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLbMaxMin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLbClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlCMHLayout.setVerticalGroup(
            jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCMHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbMaxMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPnlBg.add(jPnlCMH, java.awt.BorderLayout.PAGE_START);

        dskEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jPnlBg.add(dskEscritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPnlBg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para cerrar el formulario
     *
     * @param evt Evento del boton cerrar
     */
    private void jLbClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLbClose1MouseClicked

    /**
     * Boton para Maximizar o Minimizar el formulario
     *
     * @param evt Evento del boton Max Min form
     */
    private void jLbMaxMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbMaxMinMouseClicked

        if (state) {
            this.setExtendedState(NORMAL);
            state = !state;
        } else {
            this.setExtendedState(MAXIMIZED_BOTH);
            state = !state;
        }
    }//GEN-LAST:event_jLbMaxMinMouseClicked

    /**
     * Boton para ocultar el formulario
     *
     * @param evt Evento del boton ocultar
     */
    private void jLbHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbHideMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLbHideMouseClicked

    /**
     * Metodo encargado de capturar las coordenadas del raton para poder mover
     * el formulario
     *
     * @param evt Evento del Mouse pressed
     */
    private void jPnlCMHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCMHMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPnlCMHMousePressed

    /**
     * Metodo encargado de insertar las coordenada del formulario para ubicar el
     * formulario luego de mover con el raton
     *
     * @param evt Evento del mouse dragged
     */
    private void jPnlCMHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCMHMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPnlCMHMouseDragged

    /**
     * Boton para regresar a la pagina principal del restaurante
     *
     * @param evt Evento del boton home
     */
    private void BtnHomePageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomePageMousePressed
        setColor(BtnHomePage);
        resetColor(BtnProductos);
        resetColor(BtnProveedores);
        resetColor(BtnInsumos);
        resetColor(BtnClientes);
        resetColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        cerrarFormularios("Home");
    }//GEN-LAST:event_BtnHomePageMousePressed

    /**
     * Boton que despliega los restaurantes que estan disponibles
     *
     * @param evt Evento del boton restaurante disponibles
     */
    private void BtnProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProductosMousePressed
        resetColor(BtnHomePage);
        setColor(BtnProductos);
        resetColor(BtnProveedores);
        resetColor(BtnInsumos);
        resetColor(BtnClientes);
        resetColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        if (!ventaProductos.isVisible()) {
            cerrarFormularios("Productos");
            if (!dskEscritorio.isAncestorOf(ventaProductos)) {
                dskEscritorio.add(ventaProductos);
            } else {
                dskEscritorio.setSelectedFrame(ventaProductos);
            }
            ventaProductos.show();
        }

    }//GEN-LAST:event_BtnProductosMousePressed

    /**
     * Boton que despliega los menus del dia
     *
     * @param evt Evento del boton menus
     */
    private void BtnProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProveedoresMousePressed
        resetColor(BtnHomePage);
        resetColor(BtnProductos);
        setColor(BtnProveedores);
        resetColor(BtnInsumos);
        resetColor(BtnClientes);
        resetColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        if (!ventanaProveedores.isVisible()) {
            cerrarFormularios("Proveedores");
            ventanaProveedores.setMaximizable(true);
            if (!dskEscritorio.isAncestorOf(ventanaProveedores)) {
                dskEscritorio.add(ventanaProveedores);
            } else {
                dskEscritorio.setSelectedFrame(ventanaProveedores);
            }
            ventanaProveedores.show();
        }
    }//GEN-LAST:event_BtnProveedoresMousePressed

    /**
     * Boton que despliega los clientes que hay en la base de datos
     *
     * @param evt Evento del boton
     */
    private void BtnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMousePressed
        resetColor(BtnHomePage);
        resetColor(BtnProductos);
        resetColor(BtnProveedores);
        resetColor(BtnInsumos);
        setColor(BtnClientes);
        resetColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        if (!ventanaClientes.isVisible()) {
            cerrarFormularios("Clientes");
            ventanaClientes.setMaximizable(true);
            if (!dskEscritorio.isAncestorOf(ventanaClientes)) {
                dskEscritorio.add(ventanaClientes);
            } else {
                dskEscritorio.setSelectedFrame(ventanaClientes);
            }
            ventanaClientes.show();
        }
    }//GEN-LAST:event_BtnClientesMousePressed

    /**
     * Boton que despliega las opciones para contabilidad
     *
     * @param evt Evento del boton contabilidad
     */
    private void BtnContabilidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContabilidadMousePressed
        resetColor(BtnHomePage);
        resetColor(BtnProductos);
        resetColor(BtnProveedores);
        resetColor(BtnInsumos);
        resetColor(BtnClientes);
        resetColor(BtnEmpleados);
        setColor(BtnContabilidad);

        if (!ventanaContabilidad.isVisible()) {
            cerrarFormularios("Contabilidad");
            ventanaContabilidad.setMaximizable(true);
            if (!dskEscritorio.isAncestorOf(ventanaContabilidad)) {
                dskEscritorio.add(ventanaContabilidad);
            } else {
                dskEscritorio.setSelectedFrame(ventanaContabilidad);
            }
            ventanaContabilidad.show();
        }
    }//GEN-LAST:event_BtnContabilidadMousePressed

    /**
     * Boton que despliega las opciones para platos principales
     *
     * @param evt Evento del boton platos principales
     */
    private void BtnInsumosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInsumosMousePressed
        resetColor(BtnHomePage);
        resetColor(BtnProductos);
        resetColor(BtnProveedores);
        setColor(BtnInsumos);
        resetColor(BtnClientes);
        resetColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        if (!ventanaInsumos.isVisible()) {
            cerrarFormularios("Insumos");
            ventanaInsumos.setMaximizable(true);
            if (!dskEscritorio.isAncestorOf(ventanaInsumos)) {
                dskEscritorio.add(ventanaInsumos);
            } else {
                dskEscritorio.setSelectedFrame(ventanaInsumos);
            }
            ventanaInsumos.show();
        }
    }//GEN-LAST:event_BtnInsumosMousePressed

    /**
     * Boton que despliega las opcciones de empleado
     *
     * @param evt Evento del boton
     */
    private void BtnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadosMousePressed
        resetColor(BtnHomePage);
        resetColor(BtnProductos);
        resetColor(BtnProveedores);
        resetColor(BtnInsumos);
        resetColor(BtnClientes);
        setColor(BtnEmpleados);
        resetColor(BtnContabilidad);

        if (!ventanaEmpleados.isVisible()) {
            cerrarFormularios("Empleados");
            ventanaEmpleados.setMaximizable(true);
            if (!dskEscritorio.isAncestorOf(ventanaEmpleados)) {
                dskEscritorio.add(ventanaEmpleados);
            } else {
                dskEscritorio.setSelectedFrame(ventanaEmpleados);
            }
            ventanaEmpleados.show();
        }
    }//GEN-LAST:event_BtnEmpleadosMousePressed

    /**
     * Metodo encargado de modificar un usuario donde false activa el boton
     * modificar y apaga el de registrar
     *
     * @param evt evento del raton al precionar
     */
    private void jLbUserNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbUserNameMousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }//GEN-LAST:event_jLbUserNameMousePressed

    /**
     * Boton encargado de deslogear un usuario
     *
     * @param evt Evento del boton
     */
    private void jLbLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbLogOutMousePressed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }//GEN-LAST:event_jLbLogOutMousePressed

    /**
     * Inicia el formulario del menu para el admin
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIMenuAdmin().setVisible(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(GUIMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnClientes;
    private javax.swing.JPanel BtnContabilidad;
    private javax.swing.JPanel BtnEmpleados;
    private javax.swing.JPanel BtnHomePage;
    private javax.swing.JPanel BtnInsumos;
    private javax.swing.JPanel BtnProductos;
    private javax.swing.JPanel BtnProveedores;
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JLabel jLbClientes;
    private javax.swing.JLabel jLbClientesIcon;
    private javax.swing.JLabel jLbClose1;
    private javax.swing.JLabel jLbContabilidad;
    private javax.swing.JLabel jLbContabilidadIcon;
    private javax.swing.JLabel jLbEmpleados;
    private javax.swing.JLabel jLbEmpleadosIcon;
    private javax.swing.JLabel jLbHide;
    private javax.swing.JLabel jLbHomePage;
    private javax.swing.JLabel jLbHomePageIcono;
    private javax.swing.JLabel jLbInsumos;
    private javax.swing.JLabel jLbInsumosIcon;
    private javax.swing.JLabel jLbLogOut;
    private javax.swing.JLabel jLbMaxMin;
    private javax.swing.JLabel jLbProductos;
    private javax.swing.JLabel jLbProductosIcon;
    private javax.swing.JLabel jLbProveedores;
    private javax.swing.JLabel jLbProveedoresIcon;
    private javax.swing.JLabel jLbUserName;
    private javax.swing.JLabel jLbUserPhoto;
    private javax.swing.JPanel jPnlBg;
    private javax.swing.JPanel jPnlCMH;
    private javax.swing.JPanel jPnlSide;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * Asigna un especifico a un panel
     *
     * @param panel Panel a cambiar el color
     */
    private void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));

    }

    /**
     * Metodo encargado de reiniciar un color en especifico
     *
     * @param panel Paenel al que se le reiniciara el colo
     */
    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));

    }

    /**
     * Metodo encargado de cargar varios iconos para varias etiquetas del
     * formulario
     */
    private void initIcons() {
        addIcon(jLbHomePageIcono, "src/main/java/resources/home.png");
        addIcon(jLbProductosIcon, "src/main/java/resources/restaurant.png");
        addIcon(jLbProveedoresIcon, "src/main/java/resources/restaurantMenu.png");
        addIcon(jLbInsumosIcon, "src/main/java/resources/foodDishes.png");
        addIcon(jLbClientesIcon, "src/main/java/resources/customers.png");
        addIcon(jLbEmpleadosIcon, "src/main/java/resources/users.png");
        addIcon(jLbContabilidadIcon, "src/main/java/resources/accounting.png");
        addIcon(jLbUserPhoto, "src/main/java/resources/userPhoto.png");
    }

    /**
     * Metodo encargado de cargar un icono para una etiquetas
     *
     * @param lb Etiqueta que funciona como icono
     * @param pathIcon Direccion donde se encuentra el icono
     */
    private void addIcon(JLabel lb, String pathIcon) {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }

    /**
     * Carga un lista a traves de un socket
     */
    private void cargarLista() {

    }

    /**
     * Cierra los formularios abiertos deacuerdo al boton
     *
     * @param boton Nombre del boton
     */
    private void cerrarFormularios(String boton) {
        switch (boton) {
            case "Home":
                this.ventaProductos.setVisible(false);
                this.ventanaClientes.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Productos":
                this.ventanaClientes.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Clientes":
                this.ventaProductos.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Contabilidad":
                this.ventaProductos.setVisible(false);
                this.ventanaClientes.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Empleados":
                this.ventaProductos.setVisible(false);
                this.ventanaClientes.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Insumos":
                this.ventaProductos.setVisible(false);
                this.ventanaClientes.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaProveedores.setVisible(false);
                break;
            case "Proveedores":
                this.ventaProductos.setVisible(false);
                this.ventanaClientes.setVisible(false);
                this.ventanaContabilidad.setVisible(false);
                this.ventanaEmpleados.setVisible(false);
                this.ventanaInsumos.setVisible(false);
                break;
        }
    }
}
